# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/tinno/msm8937-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter garlic wimlite hs2 hs3,$(TARGET_DEVICE)),)

endif
